-- MySQL Script generated by MySQL Workbench
-- Wed Apr 21 19:39:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `image` VARCHAR(255) NOT NULL DEFAULT 'https://i.ibb.co/dpNjfS7/default-avatar.png',
  `admin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`code` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_sale` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author` INT NOT NULL,
  `category` INT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL,
  `price` FLOAT NOT NULL,
  `image` VARCHAR(255) NOT NULL DEFAULT 'https://i.ibb.co/5cX1fH5/default-placeholder.png',
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_prducts_sales_users_idx` (`author` ASC),
  INDEX `fk_prducts_sales_categories1_idx` (`category` ASC),
  CONSTRAINT `fk_product_author`
    FOREIGN KEY (`author`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category`)
    REFERENCES `mydb`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author` INT NOT NULL,
  `category` INT NULL,
  `post` INT NULL,
  `title` VARCHAR(100) NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  `resolved` TINYINT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_post_user1_idx` (`author` ASC),
  INDEX `fk_post_post1_idx` (`post` ASC),
  INDEX `fk_post_category1_idx` (`category` ASC),
  CONSTRAINT `fk_post_author`
    FOREIGN KEY (`author`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_parent`
    FOREIGN KEY (`post`)
    REFERENCES `mydb`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_category`
    FOREIGN KEY (`category`)
    REFERENCES `mydb`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reaction` (
  `post` INT NOT NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`post`, `user`),
  INDEX `fk_post_has_user_user1_idx` (`user` ASC),
  INDEX `fk_post_has_user_post1_idx` (`post` ASC),
  CONSTRAINT `fk_post_reaction_author`
    FOREIGN KEY (`post`)
    REFERENCES `mydb`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_reaction_post`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `latitude` VARCHAR(255) NOT NULL,
  `longitude` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`route` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author` INT NOT NULL,
  `origin` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `price` FLOAT NOT NULL,
  `seats` INT NOT NULL DEFAULT 1,
  `date` DATETIME NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_route_user1_idx` (`author` ASC),
  INDEX `fk_route_location1_idx` (`origin` ASC),
  CONSTRAINT `fk_route_author`
    FOREIGN KEY (`author`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_route_location`
    FOREIGN KEY (`origin`)
    REFERENCES `mydb`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`route_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`route_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `origin` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL,
  `days` CHAR(5) NOT NULL DEFAULT '11111',
  PRIMARY KEY (`id`),
  INDEX `fk_route_group_location1_idx` (`origin` ASC),
  CONSTRAINT `fk_group_origin`
    FOREIGN KEY (`origin`)
    REFERENCES `mydb`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manage` (
  `route_group` INT NOT NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`route_group`, `user`),
  INDEX `fk_route_group_has_user_user1_idx` (`user` ASC),
  INDEX `fk_route_group_has_user_route_group1_idx` (`route_group` ASC),
  CONSTRAINT `fk_manage_group`
    FOREIGN KEY (`route_group`)
    REFERENCES `mydb`.`route_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manage_author`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`belongs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`belongs` (
  `route_group` INT NOT NULL,
  `user` INT NOT NULL,
  `confirmed` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`route_group`, `user`),
  INDEX `fk_route_group_has_user_user2_idx` (`user` ASC),
  INDEX `fk_route_group_has_user_route_group2_idx` (`route_group` ASC),
  CONSTRAINT `fk_belongs_group`
    FOREIGN KEY (`route_group`)
    REFERENCES `mydb`.`route_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_belongs_user`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rental` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author` INT NOT NULL,
  `location` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rental_user1_idx` (`author` ASC),
  INDEX `fk_rental_location1_idx` (`location` ASC),
  CONSTRAINT `fk_rental_author`
    FOREIGN KEY (`author`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rental_location`
    FOREIGN KEY (`location`)
    REFERENCES `mydb`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
